version: '3'

services:
  continuum-server:
    image: equals215/ftb-continuum-server
    restart: unless-stopped
    build:
      dockerfile: ${API_DOCKER_FILE:-Dockerfile}
      context: ${API_DOCKER_CONTEXT:-.}
    ports:
      - 25565:25565
    environment:
      - JAVACMD=${JAVACMD:-java}
      - MAX_RAM=${MAX_RAM:-2048M}
      - JAVA_PARAMETERS=${JAVA_PARAMETERS:-"-XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=5 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10"}
    volumes:
      - $PWD/files/backups/:/ftb-server/backups/
      - $PWD/files/config/:/ftb-server/config/
      - $PWD/files/journeymap/:/ftb-server/journeymap/
      - $PWD/files/local/:/ftb-server/local/
      - $PWD/files/logs/:/ftb-server/logs/
      - $PWD/files/scripts/:/ftb-server/scripts/
      - $PWD/files/world/:/ftb-server/world/
    container_name: ftb-continuum-server
    hostname: continuum-server
